### ISSUE TITLE
Undocumented special [PAD] token in tokenizer.

### ISSUE THREAD

**Issue by alidadsetan** [microsoft/analysing_pii_leakage#13]
https://github.com/microsoft/analysing_pii_leakage/blob/04ce67b4adf5141f99beab7471688d6d6e18a77a/src/pii_leakage/models/language_model.py#L101

Hi. Here an special token has been added, which is not documented in the paper. Is this necessary for replication?

**Comment by s-zanella** [comment]
This is needed to pad inputs to GPT-2 for generation because the tokenizer doesn't define a padding token. It follows advise in the Transformers library.

https://github.com/huggingface/transformers/blob/98dda8ed03ac3f4af5733bdddaa1dab6a81e15c1/src/transformers/tokenization_utils_base.py#L2709

You can likely set it to any other existing token rather than adding a new special token, but this makes padded sequences easier to read.
